spring:
  data:
    redis:
      host: 192.168.150.130
      port: 6379
      password: 123
      timeout: 2000
      database: 0
      lettuce:
        max-active: 8
        max-idle: 8
        min-idle: 0
        timeout: 2000