spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


app:
  redis:
    loadBatchSize: 100
    expirationSeconds:
      default: 300
      filmText: 10
    lock:
      seconds: 60
      max-retries: 10
      sleep-millis: 5000