app:
  redis:
    loadBatchSize: 100
    expirationSeconds:
      default: 300
      filmText: 10
    lock:
      seconds: 60
      max-retries: 10
      sleep-millis: 5000


spring:
  data:
    redis:
      host: 192.168.150.130
      port: 6379
      password: 123